# GENERAL
GPU: 0
MODE: 'prompt' # encoder, decoder, prompt, save_features
CKPT: 'bin/mobile_sam.pt' # 'bin/mobile_sam.pt'
EXP: 'prompt'
PROFILE: False
DEBUG: False
TEST: False

# DATA
DATA_DIR: '../Datasets/'
SPLIT: 'sa_000020'
TRAIN_SPLITS: 1
MAX_TEST: 2500
BATCH_SIZE: 16
WORKERS: 8
SHUFFLE: True
LOAD_FEATURES: True

# PROMPTS
PROMPTS: 1
RANDOM_PROMPT: False
EDGE_FILTER: False
SIZE_THR_LOW: 1.e-4 # 0
SIZE_THR_HIGH: 5.e-4 # 1

# TRAINING
EPOCHS: 20
LR: 1.e-4
OPTIM: 'adam'
SCHEDULER: 'cos'
DECAY: 1.0
WD: 1.e-5
LOSS_WEIGHTS: [0,0,0,1,0,0,0] # self.FW, self.DW, self.BW, self.IW, self.MW, self.SW, self.GW 
ADD_PROMPT: 'random' # size, random