# GENERAL
GPU: 2
SEED: 0
MODE: 'prompt' # encoder, decoder, prompt, save_features
MODEL: 'mobile_sam' # mobile_sam, mobile_sam_prompt
CKPT: 'bin/mobile_sam.pt' # 'bin/mobile_sam.pt'
EXP: 'gt'
PROFILE: False
DEBUG: False
TEST: False

# DATA
DATA_DIR: '../Datasets/'
SPLIT: 'sa_000020'
TRAIN_SPLITS: 1
MAX_TEST: 2500
BATCH_SIZE: 16
WORKERS: 8
SHUFFLE: True
LOAD_FEATURES: True

# PROMPTS
PROMPTS: 1
RANDOM_PROMPT: False
EDGE_FILTER: False
SIZE_THRESHOLDS: [1.e-4, 5.e-4] # (0, 1)

# TRAINING
EPOCHS: 20
LR: 1.e-3
OPTIM: 'adam'
SCHEDULER: 'cos'
DECAY: 1.0
WD: 1.e-5
LOSS_WEIGHTS: [0,0,0,0,0,0,1] # self.FW, self.DW, self.BW, self.IW, self.MW, self.SW, self.GW 
ADD_PROMPT: 'random' # size, random