# GENERAL
GPU: 6
MODE: 'decoder' # encoder, decoder, save_features
CKPT: "bin/mobile_sam.pt" # "bin/mobile_sam.pt"
EXP: 'gt'
PROFILE: False
DEBUG: False

# DATA
DATA_DIR: '../Datasets/'
SPLIT: 'sa_000020'
TRAIN_SPLITS: 1
MAX_TEST: 2500
BATCH_SIZE: 16
NUM_WORKERS: 8
SHUFFLE: True
LOAD_FEATURES: True

# PROMPTS
N_PROMPTS: 1
RANDOM_PROMPT: False
EDGE_FILTER: False
SIZE_THR: 1.e-4

# TRAINING
EPOCHS: 20
LR: 3.e-6
OPTIM: 'adam'
SCHEDULER: 'cos'
DECAY: 1.0
WD: 1.e-5
LOSS_WEIGHTS: [0,0,0,0,0,0,1] # self.FW, self.DW, self.BW, self.IW, self.MW, self.SW, self.GW 
SIZE_EMBEDDING: 'none' # sparse, dense