# GENERAL
GPU: 0
SEED: 0
PROFILE: False
DEBUG: False

# IMPORTANT
MODE: 'prompt' # encoder, decoder, prompt, save_features
MODEL: 'mobile_sam' # mobile_sam, mobile_sam_prompt
CKPT: 'bin/mobile_sam.pt' # 'bin/mobile_sam.pt'
EXP: ''
TEST: False
SIZE_THRESHOLDS: [1.e-4, 5.e-4] # (0, 1)
LOSS_WEIGHTS: [0,0,0,0,0,0,1] # self.FW, self.DW, self.BW, self.IW, self.MW, self.SW, self.GW 
ADD_PROMPT: 'random' # size, random

# DATA
DATA_DIR: '../Datasets/'
SPLIT: 'sa_000020'
TRAIN_SPLITS: 1
MAX_TEST: 2500
BATCH_SIZE: 16
WORKERS: 8
SHUFFLE: True
LOAD_FEATURES: True

# PROMPTS
PROMPTS: 1
RANDOM_PROMPT: False
EDGE_FILTER: False

# TRAINING
EPOCHS: 20
LR: 1.e-3
OPTIM: 'adamw'
SCHEDULER: 'none'
DECAY: 1.0
WD: 1.e-5

# METRICS
TRAIN:
  LOSS: []
  IOU: []
  GT_IOU: []
VAL:
  IOU: []
  GT_IOU: []
IOU: 0
GT_IOU: 0
